// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://h3plzg2uvva3peb2zntfzt7udy.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ugyg4jhqgnbs3ofiulvkhxhtya",
    "aws_cognito_identity_pool_id": "eu-west-1:3a5e5d88-bdb8-4178-bd69-fad8f381fc4e",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_VbDMglud1",
    "aws_user_pools_web_client_id": "1n5p4g1sft6t64dn2uooi8892l",
    "oauth": {}
};


export default awsmobile;
